language: yaml

services:
  - docker

before_install:
  - docker build -t abizon/lemonldapng-manager .
  - docker run -d -p 127.0.0.1:80:80 abizon/lemonldapng-manager /bin/sh -c "/entrypoint.sh"
  - docker ps -a

script:
  - echo OK